Webpack 5 Update
stirling-brandworks/slab pull request #30
Opened 2021-11-03 15:30 UTC by DimitriMichel

This updates Webpack Version 3 to Webpack Version 5 and corresponding dependencies which were out of date were updated, and deprecated dependencies were removed.

2021-11-04 15:08 UTC, brianjohnhanna requested changes
Great work on this. Everything seems to be building smoothly and faster. Left a couple things for you to look at and update but other than that this seems okay to merge.

- I don't see the `.nvmrc` file updated to Node 16 as part of this update. If you have confirmed it also resolves #13 then you should include the update NVM config file with the appropriate node version.
- Did you test with adding images in the CSS such as `background-image: url('../images/...')`. I want to make sure this doesn't cause any issues with that.

2021-11-04 15:08 UTC, brianjohnhanna commented on package.json
> +    "node": ">=12.0.0",
I see that you claimed compatibility with Node 16 (#13) as part of this PR. If that's the case, you should pin the Node version here to ensure compatibility instead of specifying an open-ended "greater-than" range.

```json
"engines": {
  "node": "^16"
}
```

2021-11-04 15:08 UTC, brianjohnhanna commented on resources/assets/build/config.js
> +const userConfig = merge(desire(`${__dirname}/../config`), desire(`${__dirname}/../config-local`) ? desire(`${__dirname}/../config-local`) : {});
Looking at the `desire()` function, it takes a second param as a fallback if the dependency can't be resolved. Given that, I think this could be cleaned up to look like this:

```js
merge(desire(`${__dirname}/../config`), desire(`${__dirname}/../config-local`, {}));
```

2021-11-04 15:08 UTC, brianjohnhanna commented on resources/assets/build/config.js
> + *   wp_localize_script('sage/main.js', 'SAGE_DIST_PATH', get_theme_file_uri('dist/'))
I think we probably want to leave this as "slab/main.js" since that's what the JS file handle is called in `app/setup.php`

2021-11-04 15:08 UTC, brianjohnhanna commented on resources/assets/build/postcss.config.js
> +module.exports = (api) => {
I don't think the `cssnanoConfig` has to be part of the exported function, since it doesn't rely on any of the arguments to make it's config object. I would have left it where it was.

Also, we should keep using the destructuring to clean this up a little. Looks like you just needed to add the `ctx` property of the options object.

For example...

```js
const cssnanoConfig = {
  preset: ['default', { discardComments: { removeAll: true } }]
};

module.exports = ({ options }) => {
  return {
    parser: options.ctx.enabled.optimize ? 'postcss-safe-parser' : undefined,
    plugins: {
      autoprefixer: true,
      cssnano: options.ctx.enabled.optimize ? cssnanoConfig : false,
    },
  };
};
```

2021-11-04 15:08 UTC, brianjohnhanna commented on resources/assets/build/webpack.config.js
> +        //
Looks like you left an empty comment in here

2021-11-04 15:08 UTC, brianjohnhanna commented on resources/assets/build/webpack.config.js
> +                name: `[path]${assetsFilenames}.[ext]`,
I noticed that the old loader config for resources imported from node_modules used `name: ${config.cacheBusting}.[ext],` as opposed to the  `[path]${assetsFilenames}.[ext]` to make sure these assets are cache-busted with a unique filename. Did this not work with the new config or was this just an oversight?

2021-11-04 15:08 UTC, brianjohnhanna commented on package.json
> +    "copy-webpack-plugin": "^9.0.1",
This is a `devDependency`, move it to the appropriate section

2021-11-04 15:08 UTC, brianjohnhanna commented on resources/assets/build/webpack.config.js
> +                    sourceMap: true, //config.enabled.sourceMaps, // false causes a resolve issue
I wasn't able to reproduce the `sourceMap: false` when setting to `sourceMap: config.enabled.sourceMaps` and running `yarn dev` (which sets it to false aka `!inProduction`).

Can you test again and if it's working now for you make sure to change it back to pull from the config value?

2021-11-09 16:02 UTC, DimitriMichel commented
@brianjohnhanna I think most recent commit made a few changes to some loaders, those were just for compatibility, tested & still works on node ^1

2021-11-10 15:15 UTC, brianjohnhanna approved these changes
Made a couple updates myself but otherwise LGTM. Nice work.

2021-11-10 15:15 UTC, merged